version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    ports:
      - 1004:3002 
    environment:
      OPENAI_ACCESS_TOKEN: 123123sada
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, code-davinci-00

      # 反向代理，可选，默认
      API_REVERSE_PROXY: https://ai.fakeopen.com/api/conversation
      # 访问权限密钥，可选，自定义
      AUTH_SECRET_KEY: chatppp
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 1000
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      #SOCKS_PROXY_HOST: http://127.0.0.1
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      #SOCKS_PROXY_PORT: 40000
      # HTTPS 代理，可选，支持 http，https，socks5
      # HTTPS_PROXY: http://xxx:7890

